### ISSUE TITLE
Missing credit - possible DMCA

### ISSUE THREAD

**Issue by TheMeinerLP** [PoloServices/PoloCloud#38]
They currently missing credits are some classes from the commit yesterday.
[https://github.com/PoloServices/PoloCloud/commit/3d3cc1b6882aa96bae476c5ff6187a1a90e53ff0](https://github.com/PoloServices/PoloCloud/commit/3d3cc1b6882aa96bae476c5ff6187a1a90e53ff0)
Pls add credits where are the code from.

Be friendly for everyone

**Comment by derklaro** [comment]
Hi,

I just want to point out that a note in one of the files is not sufficient to be compliant with CloudNet's license (Apache License, version 2). We at CloudNet already use a relatively open license that allows our code to be adopted, but the following things must be adhered to:

 * include a copy of the Apache license
 * indicate in a conspicuous place that modified files have been modified
 * retain all original copyright notices in the source form

(Source: https://de.wikipedia.org/wiki/Apache-Lizenz)

(Related to all our transformers and associated classes, as well as in the wrapper the addTransformer methods. Also it looks like our class-pre-load logic was taken over https://github.com/CloudNetService/CloudNet-v3/blob/unstable/rewrite/wrapper-jvm/src/main/java/eu/cloudnetservice/cloudnet/wrapper/Premain.java#L41-L60 vs. https://github.com/PoloServices/PoloCloud/blob/master/cloudsystem-wrapper/src/main/java/de/polocloud/wrapper/Wrapper.java#L60-L72).

We don't want to sound like everything was taken from us. I think it's cool if you use our ideas and they help you, but please also appreciate the time we invest to find and implement these ideas.

Thanks!

**Comment by HttpMarco** [comment]
Hey, 

We have tried to live up to all agreements and have implemented all references.

Regarding the class-pre-load, I can only say that this logic has been following us for over a year and it has been in this cloud since the first version. But we will look for another solution.

I would appreciate feedback if all aspects are correct so that we don't get any issues.
Thanks!

**Comment by TheMeinerLP** [comment]
Re-open it

**Comment by derklaro** [comment]
> Regarding the class-pre-load, I can only say that this logic has been following us for over a year and it has been in this cloud since the first version. But we will look for another solution.

I just took a look through the git history, looks like the pre-load was added along with the 1.18 support (which needs it) on 7.2.2022 (commit: https://github.com/PoloServices/PoloCloud/commit/962482221e3f6b114a0db26155939cb34acec2b7), we've added the same logic on 1.12.2021 (commit: https://github.com/CloudNetService/CloudNet-v3/commit/917d19898db59818f2b0fba400e4de2c3a55e98a)

**Comment by HttpMarco** [comment]
That is ture. 
I can't say much about it because the commit didn't come from me. I noted it and that should solve it. But I will take care that such an implementation is no longer supported by us.

Do you agree with this or are there any other problems? Otherwise I would close it.

**Comment by derklaro** [comment]
If all transformers now have the license information it's okay for me 🤷 . I didn't look through the complete code, just noted that one thing while looking through the transformer addition commit :)

**Comment by HttpMarco** [comment]
Thanks for the attention., Thank you :) 🥰

**Comment by 0utplay** [comment]
Hey, sorry to interrupt again.
I took another look and noticed that not all classes contain the CloudNet information e.g. ([here](https://github.com/PoloServices/PoloCloud/blob/master/cloudsystem-wrapper/src/main/java/de/polocloud/wrapper/transformer/Transformer.java)).
In addition, the classes should keep the original copyright header.

Thanks

**Comment by RealBauHD** [comment]
https://github.com/PoloServices/PoloCloud/commit/924e51b57fabbf39b2cb83edb189a3d7067042f3

**Comment by 0utplay** [comment]
@RealBauHD I thought of you adding this comment to all classes & methods, the one mentioned was just as an example.

**Comment by RealBauHD** [comment]
To which classes?

**Comment by derklaro** [comment]
All classes in the transformer package, as I said already yesterday. And please retain all original copyright notices in the source form as the Apache License requests.

**Comment by HttpMarco** [comment]
hey,
we will remove any methods and classes. Because we prefer to work out our own solution and try to use reflections for it. We would rather continue to work diligently than deal with such issues. We didn't expect a line of code to be checked by you.

We'd rather advocate fun than paying attention everywhere. I can totally understand you too.

**Comment by 0utplay** [comment]
Okay, that's also a possibility, of course.
But then I would also ask you to remove the code completely.
The whole thing also affects the class loading of the application.

https://github.com/PoloServices/PoloCloud/blob/5c428a19df878b094ff2493861f1fd8104a28d0b/cloudsystem-wrapper/src/main/java/de/polocloud/wrapper/Wrapper.java#L55-L66

**Comment by HttpMarco** [comment]
https://github.com/PoloServices/PoloCloud/commit/4c3d7a15a09585353d2a26b0c928b82dc57b7c74
